#!/usr/bin/env python3
"""
01d_add_extra_positives.py -- merge manually-curated extra positive
sequences (e.g. Bakta hits from one of the user's own metagenome studies
that this repo's own tool missed) into each family's fetched positive set,
before CD-HIT clustering (02_cluster_cdhit.sh) dedupes the combined pool.

Motivating case: cross-checking a study's assemblies with Bakta turned up
real mazG/mscS/trkA/trkH hits that this repo's own detector missed --
exactly the kind of false negative a broader reference set should help
close. These aren't UniProt entries (no accession, no organism), so they're
retagged into the same "tag|id|organism" header convention retag_fasta()
uses (see 01_fetch_refs.py) with a distinct "<family>_study" tag so they
stay traceable to their source, the Bakta locus tag as id, and "unknown" as
organism (matches retag_fasta's own fallback for headers with no OS=/OX=).

Looks for one FASTA per family in extra_sequences/<family>.faa (gitignored
-- these are local study data, not fetched/regenerated by the pipeline).
A family with no matching file is left untouched. Safe to re-run: sequences
already present (matched by id) are not re-appended.

Usage:
  python 01d_add_extra_positives.py --refs refs --families families.yaml \\
      --extra extra_sequences
Output:
  refs/<family>.positive.faa           (extra sequences appended in place)
  refs/extra_positives_manifest.tsv
"""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path

import yaml

LOCUS_TAG_RE = re.compile(r"__([A-Za-z0-9]+_[0-9]+)")


def load_family_names(path: Path) -> list[str]:
    with open(path) as fh:
        data = yaml.safe_load(fh)
    return [fam["name"] for fam in data["families"]]


def parse_fasta(path: Path) -> list[tuple[str, str]]:
    records = []
    header, chunks = None, []
    if not path.exists():
        return records
    for line in path.read_text().splitlines():
        if line.startswith(">"):
            if header is not None:
                records.append((header, "".join(chunks)))
            header, chunks = line[1:], []
        elif line.strip():
            chunks.append(line.strip())
    if header is not None:
        records.append((header, "".join(chunks)))
    return records


def append_fasta(path: Path, records: list[tuple[str, str]]) -> None:
    with open(path, "a") as fh:
        for header, seq in records:
            fh.write(f">{header}\n")
            for i in range(0, len(seq), 60):
                fh.write(seq[i:i + 60] + "\n")


def extra_id(header: str) -> str:
    """Bakta-style header: '<bin>__<locus_tag> <product>'. Use the locus tag
    as the id field -- unique within a study, stable across reruns. Falls
    back to the first whitespace token if a future extra file doesn't
    follow that naming scheme."""
    match = LOCUS_TAG_RE.search(header)
    return match.group(1) if match else header.split()[0]


def existing_ids(records: list[tuple[str, str]]) -> set[str]:
    ids = set()
    for header, _ in records:
        parts = header.split("|")
        ids.add(parts[1] if len(parts) >= 2 else header)
    return ids


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--refs", type=Path, default=Path("refs"))
    ap.add_argument("--families", type=Path, default=Path("families.yaml"))
    ap.add_argument("--extra", type=Path, default=Path("extra_sequences"),
                     help="Directory of <family>.faa files with extra positives to merge in")
    args = ap.parse_args()

    if not args.extra.is_dir():
        print(f"No {args.extra}/ directory found -- nothing to merge.")
        return

    families = set(load_family_names(args.families))
    manifest_rows = []

    for extra_path in sorted(args.extra.glob("*.faa")):
        family = extra_path.stem
        if family not in families:
            print(f"[{extra_path.name}] SKIP: '{family}' is not a family in {args.families}")
            continue

        pos_path = args.refs / f"{family}.positive.faa"
        if not pos_path.exists():
            print(f"[{family}] SKIP: {pos_path} does not exist yet -- run 01_fetch_refs.py first")
            continue

        extra_records = parse_fasta(extra_path)
        current_ids = existing_ids(parse_fasta(pos_path))

        to_add = []
        n_dupe = 0
        for header, seq in extra_records:
            record_id = extra_id(header)
            if record_id in current_ids:
                n_dupe += 1
                continue
            to_add.append((f"{family}_study|{record_id}|unknown", seq))
            current_ids.add(record_id)

        append_fasta(pos_path, to_add)
        print(f"[{family}] {len(extra_records)} extra sequences: "
              f"{len(to_add)} appended, {n_dupe} already present (skipped)")

        manifest_rows.append({
            "family": family,
            "n_extra_total": len(extra_records),
            "n_appended": len(to_add),
            "n_already_present": n_dupe,
        })

    if not manifest_rows:
        print("No extra positive files matched a known family.")
        return

    manifest_path = args.refs / "extra_positives_manifest.tsv"
    with open(manifest_path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(manifest_rows[0].keys()), delimiter="\t")
        writer.writeheader()
        writer.writerows(manifest_rows)

    n_total = sum(r["n_appended"] for r in manifest_rows)
    print(f"\nDone. {n_total} extra positive sequences merged across {len(manifest_rows)} families.")
    print(f"Manifest: {manifest_path}")


if __name__ == "__main__":
    main()
